# Домашнее задание к уроку 1: Основы PyTorch

## Цель задания
Закрепить навыки работы с тензорами PyTorch, изучить основные операции и научиться решать практические задачи.


## Задание 1: Создание и манипуляции с тензорами (25 баллов)

Создайте файл `homework_tensors.py` и выполните следующие задачи:

In [74]:
import torch
import numpy as np
import time

### 1.1 Создание тензоров (7 баллов)
```python
# Создайте следующие тензоры:
# - Тензор размером 3x4, заполненный случайными числами от 0 до 1
# - Тензор размером 2x3x4, заполненный нулями
# - Тензор размером 5x5, заполненный единицами
# - Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)

In [41]:
tensor_rand = torch.randint(0, 2, (3,4))
tensor_zeros = torch.zeros(2,3,4)
tensor_ones = torch.ones(5,5)
tensor_with_reshape = torch.arange(0, 16, 1).reshape(4, 4)
print("Тензор заполненный случайными числами от 0 до 1:\n", tensor_rand)
print("\nТензор заполненный нулями:\n", tensor_zeros)
print("\nТензор заполненный единицами:\n", tensor_ones)
print("\nТензор размером 4x4:\n", tensor_with_reshape)

Тензор заполненный случайными числами от 0 до 1:
 tensor([[1, 1, 1, 0],
        [1, 1, 0, 0],
        [1, 0, 1, 1]])

Тензор заполненный нулями:
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Тензор заполненный единицами:
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

Тензор размером 4x4:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


### 1.2 Операции с тензорами (6 баллов)
```python
# Дано: тензор A размером 3x4 и тензор B размером 4x3
# Выполните:
# - Транспонирование тензора A
# - Матричное умножение A и B
# - Поэлементное умножение A и транспонированного B
# - Вычислите сумму всех элементов тензора A

In [37]:
A = torch.rand(3, 4)
B = torch.rand(4, 3)
print('Исходный тензор A:\n', A)
print('\nИсходный тензор B:\n', B)
print('\nТранспонированный тензор A:\n', A.T)
print('\nМатричное умножение A и B:\n', torch.matmul(A, B))
print('\nПоэлементное умножение A и транспонированного B:\n', A*B.T)
print('\nСумма всех элементов тензора A:', torch.sum(A).item())

Исходный тензор A:
 tensor([[0.7727, 0.5725, 0.2910, 0.0985],
        [0.0095, 0.2755, 0.1734, 0.4827],
        [0.7356, 0.6747, 0.1067, 0.4525]])

Исходный тензор B:
 tensor([[0.1595, 0.5948, 0.3087],
        [0.3886, 0.0724, 0.5229],
        [0.2976, 0.5473, 0.8877],
        [0.6184, 0.2178, 0.9675]])

Транспонированный тензор A:
 tensor([[0.7727, 0.0095, 0.7356],
        [0.5725, 0.2755, 0.6747],
        [0.2910, 0.1734, 0.1067],
        [0.0985, 0.4827, 0.4525]])

Матричное умножение A и B:
 tensor([[0.4932, 0.6818, 0.8915],
        [0.4586, 0.2256, 0.7679],
        [0.6911, 0.6434, 1.1124]])

Поэлементное умножение A и транспонированного B:
 tensor([[0.1232, 0.2225, 0.0866, 0.0609],
        [0.0057, 0.0200, 0.0949, 0.1051],
        [0.2271, 0.3528, 0.0947, 0.4378]])

Сумма всех элементов тензора A: 4.64525842666626


### 1.3 Индексация и срезы (6 баллов)
```python
# Создайте тензор размером 5x5x5
# Извлеките:
# - Первую строку
# - Последний столбец
# - Подматрицу размером 2x2 из центра тензора
# - Все элементы с четными индексами
```

In [56]:
tensor = torch.rand(5, 5, 5)
print('Извлечем первую строку:', tensor[0,0])
print('Извлечем последний столбец:', tensor[:,:,-1])
print('Подматрицу размером 2x2 из центра тензора:\n', tensor[:, 1:4:2, 1:4:2])

Извлечем первую строку: tensor([0.4790, 0.4259, 0.3435, 0.3063, 0.5875])
Извлечем последний столбец: tensor([[0.5875, 0.0602, 0.2492, 0.0058, 0.7767],
        [0.6025, 0.5973, 0.3517, 0.7166, 0.1989],
        [0.4499, 0.2812, 0.3432, 0.1062, 0.1053],
        [0.1514, 0.6405, 0.0352, 0.2259, 0.1861],
        [0.3550, 0.9894, 0.1790, 0.8761, 0.9108]])
Подматрицу размером 2x2 из центра тензора:
 tensor([[[0.5046, 0.7502],
         [0.9535, 0.8688]],

        [[0.0565, 0.7312],
         [0.3574, 0.5893]],

        [[0.1770, 0.5398],
         [0.9509, 0.7663]],

        [[0.1491, 0.4735],
         [0.0100, 0.3872]],

        [[0.3001, 0.2379],
         [0.4435, 0.0895]]])


### 1.4 Работа с формами (6 баллов)
```python
# Создайте тензор размером 24 элемента
# Преобразуйте его в формы:
# - 2x12
# - 3x8
# - 4x6
# - 2x3x4
# - 2x2x2x3
```

In [61]:
tensor = torch.arange(24)
shapes = [(2, 12), (3, 8), (4, 6), (2, 3, 4), (2, 2, 2, 3)]

for shape in shapes:
    print(f'Размер {shape}:\n {tensor.reshape(shape)}\n')

Размер (2, 12):
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Размер (3, 8):
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])

Размер (4, 6):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Размер (2, 3, 4):
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Размер (2, 2, 2, 3):
tensor([[[[ 0,  1,  2],
          [ 3,  4,  5]],

         [[ 6,  7,  8],
          [ 9, 10, 11]]],


        [[[12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23]]]])



## Задание 2: Автоматическое дифференцирование (25 баллов)

Создайте файл `homework_autograd.py`:

### 2.1 Простые вычисления с градиентами (8 баллов)
```python
# Создайте тензоры x, y, z с requires_grad=True
# Вычислите функцию: f(x,y,z) = x^2 + y^2 + z^2 + 2*x*y*z
# Найдите градиенты по всем переменным
# Проверьте результат аналитически

In [66]:
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)
z = torch.tensor(4.0, requires_grad=True)

f = x**2 + y**2 + z**2 + 2*x*y*z
f.backward()

grad_x = x.grad.item()
grad_y = y.grad.item()
grad_z = z.grad.item()

print(f"Значение функции f: {f.item():.1f}")
print(f"Градиент по x: {grad_x:.1f}")
print(f"Градиент по y: {grad_y:.1f}")
print(f"Градиент по z: {grad_z:.1f}")


def analytical_gradients(x_val, y_val, z_val):
    df_dx = 2*x_val + 2*y_val*z_val
    df_dy = 2*y_val + 2*x_val*z_val
    df_dz = 2*z_val + 2*x_val*y_val
    return df_dx, df_dy, df_dz

x_val = 2.0
y_val = 3.0
z_val = 4.0

print('Градиент по каждой оси, посчитанный аналитически:', analytical_gradients(x_val, y_val, z_val))

Значение функции f: 77.0
Градиент по x: 28.0
Градиент по y: 22.0
Градиент по z: 20.0
Градиент по каждой оси, посчитанный аналитически: (28.0, 22.0, 20.0)


### 2.2 Градиент функции потерь (9 баллов)
```python
# Реализуйте функцию MSE (Mean Squared Error):
# MSE = (1/n) * Σ(y_pred - y_true)^2
# где y_pred = w * x + b (линейная функция)
# Найдите градиенты по w и b
```

In [67]:
def mse_loss(x, y_true, w, b):
    """
    Вычисляет MSE loss и градиенты по w и b
    Args:
        x: Входные данные (тензор)
        y_true: Целевые значения (тензор)
        w: Весовой коэффициент (тензор с requires_grad=True)
        b: Смещение (тензор с requires_grad=True)
    Returns:
        loss: Значение MSE
        grads: Словарь с градиентами
    """
    y_pred = w * x + b
    loss = torch.mean((y_pred - y_true)**2)
    loss.backward()
    grads = {'w': w.grad.item(), 'b': b.grad.item()}
    
    return loss.item(), grads



#пример
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
y_true = torch.tensor([2.0, 4.0, 6.0, 8.0]) 
w = torch.tensor(0.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)
loss_value, gradients = mse_loss(x, y_true, w, b)

print(f"MSE значение: {loss_value:.4f}")
print(f"Градиент по w: {gradients['w']:.4f}")
print(f"Градиент по b: {gradients['b']:.4f}")


def analytical_mse_gradients(x, y_true, w_val, b_val):
    n = len(x)
    y_pred = w_val * x + b_val
    dL_dw = (2/n) * torch.sum((y_pred - y_true) * x)
    dL_db = (2/n) * torch.sum(y_pred - y_true)
    return dL_dw.item(), dL_db.item()

b_val, w_val = 0.0, 0.0
analytical_grad_w, analytical_grad_b = analytical_mse_gradients(x, y_true, w_val, b_val)

print("\nАналитическая проверка:")
print(f"dL/dw: {analytical_grad_w:.4f}")
print(f"dL/db: {analytical_grad_b:.4f}")


MSE значение: 30.0000
Градиент по w: -30.0000
Градиент по b: -10.0000

Аналитическая проверка:
dL/dw: -30.0000
dL/db: -10.0000


### 2.3 Цепное правило (8 баллов)
```python
# Реализуйте составную функцию: f(x) = sin(x^2 + 1)
# Найдите градиент df/dx
# Проверьте результат с помощью torch.autograd.grad
```

In [71]:
x = torch.tensor(1.0, requires_grad=True)

def composite_function(x):
    return torch.sin(x**2 + 1)
f = composite_function(x)
# Метод 1: backward с сохранением графа
f.backward()
grad_backward = x.grad.item()

In [73]:
import torch
import math
x = torch.tensor(1.0, requires_grad=True)

def composite_function(x):
    return torch.sin(x**2 + 1)
f = composite_function(x)

# Метод 2: autograd.grad
grad_autograd = torch.autograd.grad(outputs=f, inputs=x)[0].item()

print(f"Значение функции в x=1: {f.item():.4f}")
print(f"Градиент (backward): {grad_backward:.6f}")
print(f"Градиент (autograd.grad): {grad_autograd:.6f}")


Значение функции в x = 1: 0.9093
Градиент (backward): -0.832294
Градиент (autograd.grad): -0.832294


## Задание 3: Сравнение производительности CPU vs CUDA (20 баллов)

Создайте файл `homework_performance.py`:


### 3.1 Подготовка данных (5 баллов)
```python
# Создайте большие матрицы размеров:
# - 64 x 1024 x 1024
# - 128 x 512 x 512
# - 256 x 256 x 256
# Заполните их случайными числами

In [78]:
import torch
import time

device = torch.device('cuda')

print("\nСоздание тензора 64x1024x1024...")
start_time = time.time()
tensor1 = torch.rand(64, 1024, 1024, device=device)
creation_time = time.time() - start_time
print(f"Создано за {creation_time:.2f} сек")

print("\nСоздание тензора 128x512x512...")
start_time = time.time()
tensor2 = torch.rand(128, 512, 512, device=device)
creation_time = time.time() - start_time
print(f"Создано за {creation_time:.2f} сек")

print("\nСоздание тензора 256x256x256...")
start_time = time.time()
tensor3 = torch.rand(256, 256, 256, device=device)
creation_time = time.time() - start_time
print(f"Создано за {creation_time:.2f} сек")


Создание тензора 64x1024x1024...
Создано за 0.02 сек

Создание тензора 128x512x512...
Создано за 0.00 сек

Создание тензора 256x256x256...
Создано за 0.00 сек


### 3.2 Функция измерения времени (5 баллов)
```python
# Создайте функцию для измерения времени выполнения операций
# Используйте torch.cuda.Event() для точного измерения на GPU
# Используйте time.time() для измерения на CPU
```

In [82]:
import torch
import time

def measure_time(operation, device, *args, **kwargs):
    """
    Измеряет время выполнения операции на указанном устройстве.
    
    Args:
        operation: Функция, время выполнения которой нужно измерить
        device: 'cpu' или 'cuda'
        *args: Позиционные аргументы для операции
        **kwargs: Именованные аргументы для операции
    
    Returns:
        execution_time: Время выполнения в миллисекундах
        result: Результат выполнения операции
    """
    start_time = None
    end_time = None
    start_event = None
    end_event = None
    
    if device == 'cuda':
        start_event = torch.cuda.Event(enable_timing=True)
        end_event = torch.cuda.Event(enable_timing=True)
        torch.cuda.synchronize()
        start_event.record()
    else:
        start_time = time.perf_counter()
    
    result = operation(*args, **kwargs)
    

    if device == 'cuda':
        end_event.record()
        torch.cuda.synchronize() 
        execution_time = start_event.elapsed_time(end_event)
    else:
        end_time = time.perf_counter()
        execution_time = (end_time - start_time) * 1000  
    
    return execution_time, result


if __name__ == "__main__":
    size = 4096
    a_cpu = torch.rand(size, size)
    b_cpu = torch.rand(size, size)
    
    def matmul_cpu():
        return torch.matmul(a_cpu, b_cpu)
    cpu_time, _ = measure_time(matmul_cpu, 'cpu')
    print(f"Время матричного умножения на CPU: {cpu_time:.2f} мс")
    
    a_gpu = a_cpu.cuda()
    b_gpu = b_cpu.cuda()
    
    def matmul_gpu():
        return torch.matmul(a_gpu, b_gpu)
    _, _ = measure_time(matmul_gpu, 'cuda')
    
    gpu_time, _ = measure_time(matmul_gpu, 'cuda')
    print(f"Время матричного умножения на GPU: {gpu_time:.2f} мс")
    print(f"Ускорение: {cpu_time/gpu_time:.2f}x")

Время матричного умножения на CPU: 494.47 мс
Время матричного умножения на GPU: 50.75 мс
Ускорение: 9.74x


### 3.3 Сравнение операций (10 баллов)
```python
# Сравните время выполнения следующих операций на CPU и CUDA:
# - Матричное умножение (torch.matmul)
# - Поэлементное сложение
# - Поэлементное умножение
# - Транспонирование
# - Вычисление суммы всех элементов

# Для каждой операции:
# 1. Измерьте время на CPU
# 2. Измерьте время на GPU (если доступен)
# 3. Вычислите ускорение (speedup)
# 4. Выведите результаты в табличном виде
```

### Пример вывода:
```
Операция          | CPU (мс) | GPU (мс) | Ускорение
Матричное умножение|   150.2  |    12.3  |   12.2x
Сложение          |    45.1  |     3.2  |   14.1x
...
```

In [19]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Используемое устройство: {device}")

size = 5000
repeats = {
    'Матричное умножение': 3,
    'Поэлементное сложение': 10,
    'Поэлементное умножение': 10,
    'Транспонирование': 100,
    'Сумма': 100
}

A_cpu = torch.randn(size, size)
B_cpu = torch.randn(size, size)

A_gpu = A_cpu.to(device)
B_gpu = B_cpu.to(device)

def measure_cpu_time(operation, repeats):
    """Измерение времени выполнения операции на CPU"""  
    start_time = time.perf_counter()
    for _ in range(repeats):
        operation()
    end_time = time.perf_counter()
    
    return (end_time - start_time) * 1000 / repeats

def measure_gpu_time(operation, repeats):
    """Измерение времени выполнения операции на GPU"""
    operation()
    torch.cuda.synchronize()
    
    start_event = torch.cuda.Event(enable_timing=True)
    end_event = torch.cuda.Event(enable_timing=True)
    start_event.record()
    for _ in range(repeats):
        operation()
    end_event.record()
    torch.cuda.synchronize()
    
    return start_event.elapsed_time(end_event) / repeats


results = []

cpu_time = measure_cpu_time(lambda: torch.matmul(A_cpu, B_cpu), repeats['Матричное умножение'])
gpu_time = measure_gpu_time(lambda: torch.matmul(A_gpu, B_gpu), repeats['Матричное умножение'])
speedup = cpu_time / gpu_time
results.append(('Матричное умножение', cpu_time, gpu_time, speedup))

cpu_time = measure_cpu_time(lambda: A_cpu + B_cpu, repeats['Поэлементное сложение'])

gpu_time = measure_gpu_time(lambda: A_gpu + B_gpu, repeats['Поэлементное сложение'])
speedup = cpu_time / gpu_time
results.append(('Поэлементное сложение', cpu_time, gpu_time, speedup))

cpu_time = measure_cpu_time(lambda: A_cpu * B_cpu, repeats['Поэлементное умножение'])
gpu_time = measure_gpu_time(lambda: A_gpu * B_gpu, repeats['Поэлементное умножение'])
speedup = cpu_time / gpu_time
results.append(('Поэлементное умножение', cpu_time, gpu_time, speedup))

cpu_time = measure_cpu_time(lambda: A_cpu.t(), repeats['Транспонирование'])
gpu_time = measure_gpu_time(lambda: A_gpu.t(), repeats['Транспонирование'])
speedup = cpu_time / gpu_time
results.append(('Транспонирование', cpu_time, gpu_time, speedup))

cpu_time = measure_cpu_time(lambda: A_cpu.sum(), repeats['Сумма'])
gpu_time = measure_gpu_time(lambda: A_gpu.sum(), repeats['Сумма'])
speedup = cpu_time / gpu_time
results.append(('Сумма', cpu_time, gpu_time, speedup))

print("\nРезультаты производительности:")
print(f"{'Операция':<25} | {'CPU (мс)':<10} | {'GPU (мс)':<10} | {'Ускорение'}")
for op, cpu, gpu, speed in results:
    cpu_str = f"{cpu:.4f}" if cpu is not None else "N/A"
    gpu_str = f"{gpu:.4f}" if gpu is not None else "N/A"
    speed_str = f"{speed:.1f}x" if speed is not None else "N/A"
    print(f"{op:<25} | {cpu_str:<10} | {gpu_str:<10} | {speed_str}")

Используемое устройство: cuda

Результаты производительности:
Операция                  | CPU (мс)   | GPU (мс)   | Ускорение
------------------------------------------------------------
Матричное умножение       | 897.8318   | 91.3203    | 9.8x
Поэлементное сложение     | 17.6869    | 1.7698     | 10.0x
Поэлементное умножение    | 18.1634    | 1.7698     | 10.3x
Транспонирование          | 0.0149     | 0.0000     | 1451.2x
Сумма                     | 3.1269     | 0.5906     | 5.3x


### 3.4 Анализ результатов (5 баллов)
```python
# Проанализируйте результаты:
# - Какие операции получают наибольшее ускорение на GPU?
# - Почему некоторые операции могут быть медленнее на GPU?
# - Как размер матриц влияет на ускорение?
# - Что происходит при передаче данных между CPU и GPU?
```

#### Какие операции получают наибольшее ускорение на GPU?
С высокой арифметической интенсивностью (матричное умножение), поэлементные операции, обработка большого объема данных
#### Почему некоторые операции могут быть медленнее на GPU?
Большие расходы на передачу данных между CPU и GPU; Операции с зависимостями данных(рекурсия);
#### Как размер матриц влияет на ускорение?
Чем больше матрица, тем выше скорость обработки. При обработке маленьких матриц может быть ситуация, что вообще нет ускорения. 
#### Что происходит при передаче данных между CPU и GPU?
Из памяти CPU передаются данные на шину, которая отправляет дальше к памяти GPU.